### ISSUE TITLE
Workaround for Github API rate limit

### ISSUE THREAD

**Issue by vivekkodira1** [praveenpuglia/github_markdown_snippets#5]
Hi,

Prolonged use results in the IP address being blocked with the message 

```json
{
  "message": "API rate limit exceeded for 103.6.156.139. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

This the plugin translates to "github API responded in an unfriendly way :/"

Is there a way I can add my personal Github token to the plugin?

**Comment by praveenpuglia** [comment]
I am not sure as to how this _snippets pack_ would cause github api call limit issue. The snippets themselves don't call the github api for any sort of markdown conversion. 

You are probably using a plugin that shows markdown preview via calling github's api and that might have reached the limit. 

A screenshot and the console(Cmd + \` or Ctrl + \`) logs from sublime text will be really helpful.

**Comment by vivekkodira1** [comment]
My mistake sorry :). I think I had more than one plugin installed and assumed wrongly that this one was failing.
